# List of radiosonde types with regexs to match them from IGRA2 metadata
meta_sonde_type_dict_list = [
    {"id": 10,
     "name": "RS VIZ TYPE A (USA)",
     "regex": "|".join([
        "VIZ \(Generic\)",
        "VIZ HYPSOMETER UNSPECIFIED",
        "VIZ ACCU-LOK UNSPECIFIED",
        "VIZ UNSPECIFIED",
        "VIZ TRANSPONDER UNSPECIFIED",
        "VIZ AN/AMT-12 UNSPECIFIED",
        "VIZ AN/AMT-4B UNSPECIFIED",
        "VIZ AN/AMT 2C",
        "VIZ AN/AMT-2C UNSPECIFIED",
        "VIZ AN/AMT-4 UNSPECIFIED",
        "VIZ -SANGAMO",
        "VIZ 1392 SERIES UNSPEC TRANSISTOR XMTR",
        "VIZ 1392",
        "VIZ 1395",
        ])},
    {"id": 11,
     "name": "RS VIZ TYPE B (USA)",
     "regex": "|".join([
        "^VIZ B$",
        "VIZ B 1492-520 NWS 1680 MHZ",
        "VIZ/SIPPICAN B2 1492-540 NWS 1680 MHZ",
        ])},
    {"id": 12,
     "name": "RS SDC (SPACE DATA CORPORATION-USA)",
     "regex": "USA SPACE DATA UNSPECIFIED"},
    {"id": 13,
     "name": "ASTOR (NO LONGER MADE-AUSTRALIA)",
     "regex": "|".join([
        "AUSTRALIA ASTOR RAYSONDE T. D. C.",
        "AUSTRALIA ASTOR 72 MHZ UNSPECIFIED",
        "AUSTRALIA ASTOR 402 MHZ UNSPECIFIED",
        "AUSTRALIA ASTOR 403 MHZ EXTERNAL THERMIS",
        "AUSTRALIA ASTOR MK I TRANSISTOR",
        "AUSTRALIA ASTOR UNSPECIFIED",
        "ASTOR 402 MHz",
        "ASTOR MARK I",
        "AUSTRALIA AWA UNSPECIFIED",
        "AUSTRALIA PHILIPS MK II LICL HYGRISTOR",
        "AUSTRALIA PHILIPS MK 2.5 CARBON HYGRISTR",
        "AUSTRALIA PHILIPS RS4 UNSPECIFIED",
        "AUSTRALIA PHILIPS MK III CARBON HYGRISTR",
        "AUSTRALIA PHILIPS UNSPECIFIED",
        "PHILIPS MK II",
        "PHILIPS RS4",
        "PHILIPS \(Generic\)",
        "AUSTRALIA ECLIPSE RADIO",
        ])},
    {"id": 14,
     "name": "VIZ MARK I MICROSONDE(USA)",
     "regex": "|".join([
        "VIZ MK I MICROSONDE OMEGA UNSPECIFIED",
        "VIZ OMEGA",
        "VIZ MK I MICROSONDE SERIES UNSPECIFIED",
        ])},
    {"id": 15,
     "name": "EEC COMPANY TYPE 23 (USA)",
     "regex": None},
    {"id": 16,
     "name": "ELIN (AUSTRIA)",
     "regex": "|".join([
        "AUSTRIA ELIN",
        ])},
    {"id": 17,
     "name": "GRAW G. (GERMANY)",
     "regex": None},
    {"id": 19,
     "name": "GRAW M60 (GERMANY)",
     "regex": "|".join([
        "GERMANY GRAW H50",
        "GRAW H50",
        "GERMANY GRAW M60 UNSPECIFIED",
        "GRAW M60",
        "GERMANY GRAW RSG78 CARBON HYGRISTOR",
        ])},
    {"id": 20,
     "name": "INDIAN MET SERVICE MK3 (INDIA)",
     "regex": "|".join([
        "INDIA MARK 3",
        "INDIA MARK 4 401 MHZ CARBON HYGRISTOR",
        "INDIA MARK 4 1680 MHZ CARBON HYGRISTOR",
        "INDIA MARK 4 1680 MHZ MODIFIED",
        "INDIA AUDIOMOD 401 MHZ NEW THERMISTOR",
        "INDIA AUDIOMOD 401 MHZ NEW HUMIDITY DUCT",
        "INDIA FAN TYPE",
        "INDIA CLOCK TYPE",
        "INDIA CLOCK 2 TRANSMITTERS 75/397 MHZ",
        "INDIA AUDIOMODULATED",
        "INDIA AUDIOMODULATED 401 MHZ",
        "INDIA AUDIOMOD 1680 MHZ NEW THERMISTOR",
        "SPECIAL: INDIA IMD RADIOMETER \+ AM1988",
        "SPECIAL: INDIA IMD RADIOMETER \+ MK3 OR 4",
        "WIND: INDIA 401 MHZ TRANSMITTER",
        ])},
    {"id": 21,
     "name": "VIZ/JIN YANG MARK I MICROSONDE(SOUTH KOREA)",
     "regex": "|".join([
        "S KOREA JINYANG VIZ 1524-511 OMEGA WIND",
        ])},
    {"id": 22,
     "name": "MEISEI RS2-80 (JAPAN)",
     "regex": "|".join([
        "JAPAN METEOR AGENCY ECHOSONDE",
        "JAPAN MEISEI UNSPECIFIED",
        "MEISEI RSII-80",
        "MEISEI-JAPAN \(G\)",
        "JAPAN MEISEI RSII-56 1680 MHZ",
        "JAPAN MEISEI RSII-91 UNSPECIFIED",
        "JAPAN MEISEI RSII-91 TYPE 94 THERMISTOR",
        "JAPAN MEISEI RSII-91 RH CORRECTION",
        "OZONE: JAPAN MEISEI RS2-KC-68 CHEMILUMIN",
        "OZONE: JAPAN MEISEI RSII-KC-79, 79D ECC",
        "OZONE: JAPAN MEISEI RSII-KC-96 ECC",
        "OZONE: JAPAN MEISEI KC-02GE GPS ECC",
        ])},
    {"id": 23,
     "name": "MESURAL FMO 1950A (FRANCE)",
     "regex": "|".join([
        "^MESURAL$",
        "FRANCE MESURAL UNSPECIFIED",
        "FRANCE MESURAL FMO 1950A",
        "MESURAL FMO 1950A",
        "MESURAL FMO 1943B",
        "FRANCE MESURAL FMO 1940B",
        "FRANCE MESURAL FMO 1944C",
        "FRANCE MESURAL FMO 1950",
        ])},
    {"id": 24,
     "name": "MESURAL FMO 19455A (FRANCE)",
     "regex": "|".join([
        "FRANCE MESURAL FMO 1955",
        ])},
    {"id": 25,
     "name": "MESURAL MH73A (FRANCE)",
     "regex": "|".join([
        "FRANCE MESURAL MH73A",
        "MESURAL MH73A",
        ])},
    {"id": 26,
     "name": "METEOLABOR BASORA (SWITZERLAND)",
     "regex": None},
    {"id": 27,
     "name": "AVK-MRZ (USSR)",
     "regex": "|".join([
        "RUSSIA/USSR MRZ-3A",
        "RUSSIA MRZ-3A ARMA",
        "RUSSIA/USSR MRZ UNSPECIFIED",
        "RUSSIA/USSR MARS OR MRZ UNSPECIFIED",
        "RUSSIA AVK-RF95-ARMA",
        "RUSSIA AVK-RF95 VAISALA SENSORS",
        ])},
    {"id": 28,
     "name": "METEORIT MARZ2-1 (USSR)",
     "regex": "|".join([
        "RUSSIA/USSR MARS UNSPECIFIED",
        "^MARS$",
        ])},
    {"id": 29,
     "name": "METEIRIT MARZ2-2 (USSR)",
     "regex": "|".join([
        "RUSSIA/USSR MARS-2-1",
        "RUSSIA/USSR MARS-2-2",
        ])},
    {"id": 30,
     "name": "OKI RS2-80 (JAPAN)",
     "regex": None},
    {"id": 31,
     "name": "VIZ/VALCOM TYPE A PRESSURE-COMMUTATED(CANADA)",
     "regex": "|".join([
        "CANADA SANGAMO UNSPECIFIED",
        ])},
    {"id": 32,
     "name": "SHANGAI RADIO (CHINA)",
     "regex": None},
    {"id": 33,
     "name": "UK MET OFFICE MK3( UK)",
     "regex": "|".join([
        "UKMO SONDE",
        "BRITAIN UNSPECIFIED",
        "BRITAIN KEW MARK I",
        "KEW MK II",
        "KEW MK IIB",
        "BRITAIN WHITELEY KEW MARK II",
        ])},
    {"id": 34,
     "name": "VINOHRADY(CZECHOSLOVAKIA)",
     "regex": None},
    {"id": 35,
     "name": "VAISALA RS18 (FINLAND)",
     "regex": "|".join([
        "VAISALA RS11",
        "VAISALA RS12 WATER INSULATED",
        "VAISALA RS13 25 MHZ",
        "VAISALA RS15 HIGHER POWER TRANSMITTER",
        "VAISALA RS13/15 UNSPECIFIED",
        "VAISALA RS18",
        ])},
    {"id": 36,
     "name": "VAISALA RS21 (FINLAND)",
     "regex": "|".join([
        "VAISALA RS21 UNSPECIFIED",
        "VAISALA RS21",
        "VAISALA UNSPECIFIED",
        "VAISALA \(Generic\)",
        ])},
    {"id": 37,
     "name": "VAISALA RS80 (FINLAND)",
     "regex": "|".join([
        "VAISALA RS 53",
        "VAISALA RS53 ERRONEOUS",
        "VAISALA RS 56",
        "VAISALA RS56 ERRONEOUS",
        "VAISALA RS 2 56",
        "VAISALA RS80",
        "VAISALA RS80 UNSPECIFIED",
        "VAISALA RS80-56H NWS SOLAR/IR CORR",
        "VAISALA RS80-15",
        "VAISALA RS90 DIGICORA 1 2 MARWIN LORAN",
        "VAISALA RS92 DIGI 1 2 MARWIN GPS WIND",
        "VAISALA RS92-SGP",
        "VAISALA RS92K",
        "VAISALA 92K",
        ])},
    {"id": 38,
     "name": "VIZ LOCATE (LORAN-C)(USA)",
     "regex": None},
    {"id": 39,
     "name": "SPRENGER E076 (GERMANY)",
     "regex": "|".join([
        "GERMANY SPRENGER UNSPECIFIED",
        ])},
    {"id": 40,
     "name": "SPRENGER E084 (GERMANY)",
     "regex": None},
    {"id": 41,
     "name": "SPRENGER E085 (GERMANY)",
     "regex": None},
    {"id": 42,
     "name": "SPRENGER E086 (GERMANY)",
     "regex": None},
    {"id": 43,
     "name": "AIR IS -4A-1680 (UK)",
     "regex": None},
    {"id": 44,
     "name": "AIR IS -4A-1680 X (UK)",
     "regex": None},
    {"id": 45,
     "name": "RS MSS(USA)",
     "regex": None},
    {"id": 46,
     "name": "AIR IS -4A-403(USA)",
     "regex": None},
    {"id": 47,
     "name": "MEISLEI RS2-91(JAPAN)",
     "regex": None},
    {"id": 48,
     "name": "VALCOM(CANADA)",
     "regex": "|".join([
        "CANADA VALCOM UNSPECIFIED",
        "CANADA CHRONOMETRIC UNSPECIFIED",
        ])},
    {"id": 49,
     "name": "VIZ MARK II(USA)",
     "regex": "|".join([
        "VIZ/SIPPICAN MICROSONDE MKIIA GPS",
        "VIZ MK II SERIES MICROSONDE UNSPECIFIED",
        ])},
    {"id": 60,
     "name": "VAISALA RS80/MICROCORA (FINLAND)",
     "regex": None},
    {"id": 61,
     "name": "VAISALA RS80/DIGCORA OR MARWIN (FINLAND)",
     "regex": None},
    {"id": 62,
     "name": "VAISALA RS80/PCCORA (FINLAND)",
     "regex": None},
    {"id": 63,
     "name": "VAISALA RS80/STAR (FINLAND)",
     "regex": None},
    {"id": 64,
     "name": "ORBITAL,SCIENCE CORPORATION,SPACE DATA DIVISION,TRANSPONDER RADIOSONDE,TYPE 909-11-XX,WHERE XX CORRECPOND TO THE MODEL OF THE INSTRUMENT",
     "regex": None},
    {"id": 65,
     "name": "VIZ TRANSPONDER RADIOSONDE,MODEL NUMBER 1499-520(USA)",
     "regex": None},
    {"id": 255,
     "name": "MISSING",
     "regex": "|".join([
        "UNKNOWN",
        "USSR RZ-049 UNSPECIFIED",
        "RZ 049",
        "USSR RKZ-1A 1780 MHZ",
        "USSR RKZ-2 1780 MHZ",
        "USSR RKZ-5 1780 MHZ",
        "USSR RKZ 1782 MHZ UNSPECIFIED",
        "RKZ 5",
        "USSR A-22 UNSPECIFIED",
        "USSR A-22-IV UNSPECIFIED",
        "USSR A-22-IV.D 403 MHZ TRANSPONDER",
        "USSR MOLCHANOV KAMMGERAET NO HUMID 1934",
        "USSR MOLCHANOV KAMMGERAET NO HUMID 1936",
        "USSR MOLCHANOV COMB KAMMGERAET NO HUMID",
        "PROFILER: RUSSIA ATTEX MICROWAVE MTP-5H",
        "CHINA GZZ-2 403 MHZ",
        "CHINA GTS1 1680 MHZ",
        "ITALY AUTOVOX 403 MHZ",
        "USA WEATHERMEASURE RD 1680 ERRONEOUS \(\?\)",
        "FRANCE METOX CT UNSPECIFIED",
        "FRANCE PRESALE 1947",
        "E GERMANY FREIBERG UNSPECIFIED",
        "METOX CT",
        "METOX GOLDBEAT.",
        "U.S.W.B. ELECTRONIC",
        "VIZ USWB ELECTRONIC UNSPECIFIED",
        "A22 SERIES",
        "A22 IV",
        "SPECIAL: USA KUHN IMPRVD RADIOMETERSONDE",
        "BENDIX",
        "DIAMOND HINMAN",
        "WIND: WIND ONLY RADAR \(PASSIVE TARGET\)",
        ])}
]
